---
- name: "Ensure that all audio users have a home directory and are in the 'audio' group"
  become: true
  user:
    name: "{{ item }}"
    append: true
    create_home: true
    groups:
      - audio
  loop: "{{ raspberrypi_audio_users }}"

- include: usb-audio-card.yml
  when:
    - raspberrypi_audio_mode == "usb_audio_card"
- include: justboom-dac.yml
  when:
    - raspberrypi_audio_mode == "justboom_dac"

- include: spi.yml

- include: shutdown-hook.yml
